### ISSUE TITLE
[BUG] An unexpected error (SteamKit2.SteamKitWebRequestException) occurred while downloading manifests

### ISSUE THREAD

**Issue by sgpublic** [tpill90/steam-lancache-prefill#372]
I also encountered the problem same as #342, here is the log:
 
```
[8:09:59 AM] Starting login!
Connecting to Steam...
[8:10:02 AM] Connected to Steam!
Logging in to Steam...
[8:10:03 AM] Logged into Steam
Retrieving owned apps...
[8:10:05 AM] Loaded account licenses                             00.9352
[8:10:05 AM] Steam session initialization complete!              05.7734
────────────────────────────────────────────────────────────────────────────────
Retrieving latest App metadata...
[8:10:09 AM] Starting Apex Legends
 Getting available CDN Servers... 
 Getting available CDN Servers...  Retrying 1
 Getting available CDN Servers...  Retrying 2
 Getting available CDN Servers...  Retrying 3
Fetching depot manifests...
[8:10:15 AM]    An unexpected error (SteamKit2.SteamKitWebRequestException) 
occurred while downloading manifests.  Retrying...
[8:10:16 AM]    An unexpected error (SteamKit2.SteamKitWebRequestException) 
occurred while downloading manifests.  Retrying...
[8:10:18 AM]    An unexpected error (SteamKit2.SteamKitWebRequestException) 
occurred while downloading manifests.  Retrying...
[8:10:20 AM] Unexpected download error : Unable to download manifests!  Skipping
app...
[8:10:20 AM] Starting DEAD OR ALIVE Xtreme Venus Vacation
 Getting available CDN Servers... 
 Getting available CDN Servers...  Retrying 1
 Getting available CDN Servers...  Retrying 2
 Getting available CDN Servers...  Retrying 3
Fetching depot manifests...
[8:10:25 AM]    An unexpected error (SteamKit2.SteamKitWebRequestException) 
occurred while downloading manifests.  Retrying...
[8:10:27 AM]    An unexpected error (SteamKit2.SteamKitWebRequestException) 
occurred while downloading manifests.  Retrying...
[8:10:29 AM]    An unexpected error (SteamKit2.SteamKitWebRequestException) 
occurred while downloading manifests.  Retrying...
[8:10:30 AM] Unexpected download error : Unable to download manifests!  Skipping
app...
...
```

docker-compose.yaml:

```yaml
version: '2'
services:
  monolithic:
    image: lancachenet/monolithic:latest
    env_file: stack.env
    restart: always
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs
    networks:
      lancachenet-network:
        ipv4_address: "192.168.6.140"
        mac_address: "02:42:ac:11:00:02"
  prefill:
    image: tpill90/steam-lancache-prefill:v2.6.0
    restart: unless-stopped
    network_mode: host
    user: 1000:1000
    volumes:
      - /mnt/core/app/steam-lancache-prefill/account-sgpublic:/Config
      - /mnt/core/app/steam-lancache-prefill/home:/Home
      - /mnt/resource/steam-cache-prefill:/.cache
    working_dir: "/Home"
    entrypoint: ["/SteamPrefill", "prefill"]
    # entrypoint: ["sleep", "10000"]

networks:
  lancachenet-network:
    driver: macvlan
    driver_opts:
      parent: enp5s0
    ipam:
      config:
        - subnet: 192.168.6.0/24
          gateway: 192.168.6.1
```

I use a transparent proxy on my network, so it should be possible to download Steam content, and I have also set up DNS on my gateway:

```
madray@nas:/mnt/core/app/steam-lancache-prefill$ nslookup lancache.steamcontent.com
Server:         192.168.6.1
Address:        192.168.6.1#53

Name:   lancache.steamcontent.com
Address: 192.168.6.140
```

It looks like lancache is not detected?
